MEDIAWIKI_API_URL = "https://www.wikidata.org/w/api.php"
# SPARQL_API_URL = "https://query.wikidata.org/sparql"
SPARQL_API_URL = "http://127.0.0.1:7001"
CACHE_DIRECTORY = "wikidata/cache"
LOG_FILENAME = "log.json"
